### ISSUE TITLE
Urban | Invalid Form Body

### ISSUE THREAD

**Issue by TypicallyShad** [Multarix/Guildbot#33]
Using the urban command to search for "dee" will result in the error below:
(https://www.urbandictionary.com/define.php?term=Dee)

```DiscordAPIError: Invalid Form Body```
```embed.fields[0].value: Must be 1024 or fewer in length.```

**Comment by Multarix** [comment]
This happens due to how the command is coded and the fact that there are certain words within urban dictionary that have a description that is over 1024 characters, the only solution I have is to trail off or simply post a link when this is encountered. 
I can work out a fix this tonight or tomorrow as my pc is currently being upgraded.

**Comment by Multarix** [comment]
This should be fixed now, thanks for reporting!
